const express = require("express");
const app = express();
const md5 = require('md5');
const conn = require("./mysql.js");
const path = require('path');
const fs = require('fs');
const bodyParser = require("body-parser");
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
require('dotenv').config();
const jwt = require("jsonwebtoken");
const cookieParser = require("cookie-parser");
const session = require("express-session");
app.use(session({ resave: false, saveUninitialized: true, secret: "your secret key" }));
app.use(cookieParser());
const SECRET_KEY = "Kajal123";
const functions = require("./Projects/component_grid/middleware.js");
const functions_df = require('./Projects/dynamic_form_creation/middleware.js');
const { PORT } = process.env;
console.log(PORT);
app.set("view engine", "ejs");

const router = require('./routes/loginSystemRoute.js');
const ticTacToeRoute = require('./routes/ticTacToeRoute.js');
const kukuCubeRouter = require('./routes/kukuCubeRoute.js');
const asyncAwaitRouter = require('./routes/asyncAwaitRouter.js');
const simpleCrudRouter = require('./routes/simpleCrudRoutes.js');
const dynamicJobAppRouter = require('./routes/dynamicJobAppRouter.js');
const searchFilter = require('./routes/searchFilter.js');
const componentGrid = require('./routes/componentGridRoute.js');
const jsEventRouter = require('./routes/jsEventRoute.js');
const dynamicComponentRouter = require('./routes/dynamicComponentsRoute.js');
const simpleSortingRoute = require('./routes/simpleSorting.js');
const dynamicCubeRouter = require('./routes/dynamicCube.js');
const paginationRouter = require('./routes/paginationRouter.js');
const studentReportRouter = require('./routes/studentReportRouter.js');
const jobAppFormRouter = require('./routes/jobAppFormRouter.js');

app.use('/', router);
app.use('/', ticTacToeRoute);
app.use('/', kukuCubeRouter);
app.use('/', asyncAwaitRouter);
app.use('/', simpleCrudRouter);
app.use('/', dynamicJobAppRouter);
app.use('/', searchFilter);
app.use('/', componentGrid);
app.use('/', jsEventRouter);
app.use('/', dynamicComponentRouter);
app.use('/', simpleSortingRoute);
app.use('/', dynamicCubeRouter);
app.use('/', paginationRouter);
app.use('/', studentReportRouter);
app.use('/', jobAppFormRouter);
app.listen(8080);